# Setup
title:               grtnr.com
tagline:             
description:         'Stuff that keeps me busy, like family, coding, math, mountains and more.'
url:                 https://grtnr.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Till Gartner
  url:               https://twitter.com/tillg
  email:             till.gartner@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-postfiles

permalink: /:year-:month-:day-:title.html

# Setting defaults for post
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  - 
    scope:
      path: "_recipes"
    values:
      excerpt_separator: "CANTFINDME!"


collections:
  recipes:
    output: true
    permalink: /:name


# Custom vars
google_analytics_id: G-H8M7YDCSD4
